//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject_Ass7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        public Trip(string tripNumber, string truckNumber, string driverNumber, string co_driverNumber, DateTime? dateDeparted, DateTime? dateReturned, string state, decimal? milesDriven, string receiptNumber, decimal? gallonsQuantity, decimal? taxesPaid, string stationName, string stationLocation)
        {
            this.tripNumber = tripNumber;
            this.truckNumber = truckNumber;
            this.driverNumber = driverNumber;
            this.co_driverNumber = co_driverNumber;
            this.dateDeparted = dateDeparted;
            this.dateReturned = dateReturned;
            this.state = state;
            this.milesDriven = milesDriven;
            this.receiptNumber = receiptNumber;
            this.gallonsQuantity = gallonsQuantity;
            this.taxesPaid = taxesPaid;
            this.stationName = stationName;
            this.stationLocation = stationLocation;
        }

        public string tripNumber { get; set; }
        public string truckNumber { get; set; }
        public string driverNumber { get; set; }
        public string co_driverNumber { get; set; }
        public Nullable<System.DateTime> dateDeparted { get; set; }
        public Nullable<System.DateTime> dateReturned { get; set; }
        public string state { get; set; }
        public Nullable<decimal> milesDriven { get; set; }
        public string receiptNumber { get; set; }
        public Nullable<decimal> gallonsQuantity { get; set; }
        public Nullable<decimal> taxesPaid { get; set; }
        public string stationName { get; set; }
        public string stationLocation { get; set; }
    }
}
